// steam_autogen.cpp: Generated by GmlCppExtFuncs. Don't touch this!
#include "gml_ext.h"
#include "steam_glue.h"
// Struct forward declarations:
// from steam_inventory.cpp:48:
struct steam_inventory_result_item {
	SteamItemInstanceID_t item_id;
	SteamItemDef_t item_def;
	uint16 quantity;
	uint16 flags;
};
// from steam_inventory.cpp:111:
struct steam_inventory_create_item_t {
	SteamItemDef_t item_def;
	uint32 quantity;
};
// from steam_inventory.cpp:115:
struct steam_inventory_destroy_item_t {
	SteamItemInstanceID_t item_id;
	uint32 quantity;
};
// from steam_inventory.cpp:294:
struct steam_inventory_get_item_prices_t {
	SteamItemDef_t item_def;
	uint64 price;
};
// from steam_user.cpp:39:
struct steam_get_friends_game_info_t {
	uint64 friendId;
	uint32 gameId;
	uint64 lobbyId;
	char name[32];
};
extern int steam_inventory_result_get_status(SteamInventoryResult_t inv_result);
dllx double steam_inventory_result_get_status_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamInventoryResult_t _arg_inv_result;
	_arg_inv_result = _buf.read<SteamInventoryResult_t>();
	return steam_inventory_result_get_status(_arg_inv_result);
}

extern int steam_inventory_result_get_unix_timestamp(SteamInventoryResult_t inv_result);
dllx double steam_inventory_result_get_unix_timestamp_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamInventoryResult_t _arg_inv_result;
	_arg_inv_result = _buf.read<SteamInventoryResult_t>();
	return steam_inventory_result_get_unix_timestamp(_arg_inv_result);
}

extern const char* steam_inventory_result_get_item_property(SteamInventoryResult_t inv_result, int item_index, const char* prop_name);
dllx const char* steam_inventory_result_get_item_property_raw(void* _ptr, const char* _arg_prop_name) {
	gml_buffer _buf(_ptr);
	SteamInventoryResult_t _arg_inv_result;
	_arg_inv_result = _buf.read<SteamInventoryResult_t>();
	int _arg_item_index;
	_arg_item_index = _buf.read<int>();
	return steam_inventory_result_get_item_property(_arg_inv_result, _arg_item_index, _arg_prop_name);
}

extern vector<steam_inventory_result_item> steam_inventory_result_get_items(SteamInventoryResult_t inv_result);
static vector<steam_inventory_result_item> steam_inventory_result_get_items_raw_vec;
dllx double steam_inventory_result_get_items_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamInventoryResult_t _arg_inv_result;
	_arg_inv_result = _buf.read<SteamInventoryResult_t>();
	steam_inventory_result_get_items_raw_vec = steam_inventory_result_get_items(_arg_inv_result);
	return (double)(4 + steam_inventory_result_get_items_raw_vec.size() * sizeof(steam_inventory_result_item));
}
dllx double steam_inventory_result_get_items_raw_post(void* _ptr) {
	gml_buffer _buf(_ptr);
	_buf.write_vector<steam_inventory_result_item>(steam_inventory_result_get_items_raw_vec);
	return 1;
}

extern bool steam_inventory_result_destroy(SteamInventoryResult_t inv_result);
dllx double steam_inventory_result_destroy_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamInventoryResult_t _arg_inv_result;
	_arg_inv_result = _buf.read<SteamInventoryResult_t>();
	return steam_inventory_result_destroy(_arg_inv_result);
}

extern SteamInventoryResult_t steam_inventory_trigger_item_drop(SteamItemDef_t item_def);
dllx double steam_inventory_trigger_item_drop_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamItemDef_t _arg_item_def;
	_arg_item_def = _buf.read<SteamItemDef_t>();
	SteamInventoryResult_t _ret = steam_inventory_trigger_item_drop(_arg_item_def);
	_buf.rewind();
	_buf.write<SteamInventoryResult_t>(_ret);
	return 1;
}

extern SteamInventoryResult_t steam_inventory_add_promo_item(SteamItemDef_t item_def);
dllx double steam_inventory_add_promo_item_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamItemDef_t _arg_item_def;
	_arg_item_def = _buf.read<SteamItemDef_t>();
	SteamInventoryResult_t _ret = steam_inventory_add_promo_item(_arg_item_def);
	_buf.rewind();
	_buf.write<SteamInventoryResult_t>(_ret);
	return 1;
}

extern SteamInventoryResult_t steam_inventory_add_promo_items(gml_vector<SteamItemDef_t> item_defs);
dllx double steam_inventory_add_promo_items_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	gml_vector<SteamItemDef_t> _arg_item_defs;
	_arg_item_defs = _buf.read_gml_vector<SteamItemDef_t>();
	SteamInventoryResult_t _ret = steam_inventory_add_promo_items(_arg_item_defs);
	_buf.rewind();
	_buf.write<SteamInventoryResult_t>(_ret);
	return 1;
}

extern SteamInventoryResult_t steam_inventory_consume_item(SteamItemInstanceID_t item_id, uint32 quantity);
dllx double steam_inventory_consume_item_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamItemInstanceID_t _arg_item_id;
	_arg_item_id = _buf.read<SteamItemInstanceID_t>();
	uint32 _arg_quantity;
	_arg_quantity = _buf.read<uint32>();
	SteamInventoryResult_t _ret = steam_inventory_consume_item(_arg_item_id, _arg_quantity);
	_buf.rewind();
	_buf.write<SteamInventoryResult_t>(_ret);
	return 1;
}

extern SteamInventoryResult_t steam_inventory_exchange_items(gml_vector<steam_inventory_create_item_t> create, gml_vector< steam_inventory_destroy_item_t> destroy);
dllx double steam_inventory_exchange_items_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	gml_vector<steam_inventory_create_item_t> _arg_create;
	_arg_create = _buf.read_gml_vector<steam_inventory_create_item_t>();
	gml_vector< steam_inventory_destroy_item_t> _arg_destroy;
	_arg_destroy = _buf.read_gml_vector<steam_inventory_destroy_item_t>();
	SteamInventoryResult_t _ret = steam_inventory_exchange_items(_arg_create, _arg_destroy);
	_buf.rewind();
	_buf.write<SteamInventoryResult_t>(_ret);
	return 1;
}

extern SteamInventoryResult_t steam_inventory_generate_items(gml_vector<steam_inventory_create_item_t> create);
dllx double steam_inventory_generate_items_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	gml_vector<steam_inventory_create_item_t> _arg_create;
	_arg_create = _buf.read_gml_vector<steam_inventory_create_item_t>();
	SteamInventoryResult_t _ret = steam_inventory_generate_items(_arg_create);
	_buf.rewind();
	_buf.write<SteamInventoryResult_t>(_ret);
	return 1;
}

extern SteamInventoryResult_t steam_inventory_get_all_items();
dllx double steam_inventory_get_all_items_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamInventoryResult_t _ret = steam_inventory_get_all_items();
	_buf.write<SteamInventoryResult_t>(_ret);
	return 1;
}

extern bool steam_inventory_request_eligible_promo_item_defs(uint64 user_id);
dllx double steam_inventory_request_eligible_promo_item_defs_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	uint64 _arg_user_id;
	if (_buf.read<bool>()) {
		_arg_user_id = _buf.read<uint64>();
	} else _arg_user_id = 0;
	return steam_inventory_request_eligible_promo_item_defs(_arg_user_id);
}

extern SteamInventoryResult_t steam_inventory_get_items_by_id(gml_vector<SteamItemInstanceID_t> item_ids);
dllx double steam_inventory_get_items_by_id_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	gml_vector<SteamItemInstanceID_t> _arg_item_ids;
	_arg_item_ids = _buf.read_gml_vector<SteamItemInstanceID_t>();
	SteamInventoryResult_t _ret = steam_inventory_get_items_by_id(_arg_item_ids);
	_buf.rewind();
	_buf.write<SteamInventoryResult_t>(_ret);
	return 1;
}

extern SteamInventoryUpdateHandle_t steam_inventory_start_update_properties();
dllx double steam_inventory_start_update_properties_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamInventoryUpdateHandle_t _ret = steam_inventory_start_update_properties();
	_buf.write<SteamInventoryUpdateHandle_t>(_ret);
	return 1;
}

extern bool steam_inventory_set_property_bool(SteamInventoryUpdateHandle_t handle, SteamItemInstanceID_t item_id, const char* prop_name, bool value);
dllx double steam_inventory_set_property_bool_raw(void* _ptr, const char* _arg_prop_name) {
	gml_buffer _buf(_ptr);
	SteamInventoryUpdateHandle_t _arg_handle;
	_arg_handle = _buf.read<SteamInventoryUpdateHandle_t>();
	SteamItemInstanceID_t _arg_item_id;
	_arg_item_id = _buf.read<SteamItemInstanceID_t>();
	bool _arg_value;
	_arg_value = _buf.read<bool>();
	return steam_inventory_set_property_bool(_arg_handle, _arg_item_id, _arg_prop_name, _arg_value);
}

extern bool steam_inventory_set_property_float(SteamInventoryUpdateHandle_t handle, SteamItemInstanceID_t item_id, const char* prop_name, float value);
dllx double steam_inventory_set_property_float_raw(void* _ptr, const char* _arg_prop_name) {
	gml_buffer _buf(_ptr);
	SteamInventoryUpdateHandle_t _arg_handle;
	_arg_handle = _buf.read<SteamInventoryUpdateHandle_t>();
	SteamItemInstanceID_t _arg_item_id;
	_arg_item_id = _buf.read<SteamItemInstanceID_t>();
	float _arg_value;
	_arg_value = _buf.read<float>();
	return steam_inventory_set_property_float(_arg_handle, _arg_item_id, _arg_prop_name, _arg_value);
}

extern bool steam_inventory_set_property_int(SteamInventoryUpdateHandle_t handle, SteamItemInstanceID_t item_id, const char* prop_name, int64 value);
dllx double steam_inventory_set_property_int_raw(void* _ptr, const char* _arg_prop_name) {
	gml_buffer _buf(_ptr);
	SteamInventoryUpdateHandle_t _arg_handle;
	_arg_handle = _buf.read<SteamInventoryUpdateHandle_t>();
	SteamItemInstanceID_t _arg_item_id;
	_arg_item_id = _buf.read<SteamItemInstanceID_t>();
	int64 _arg_value;
	_arg_value = _buf.read<int64>();
	return steam_inventory_set_property_int(_arg_handle, _arg_item_id, _arg_prop_name, _arg_value);
}

extern bool steam_inventory_set_property_string(SteamInventoryUpdateHandle_t handle, SteamItemInstanceID_t item_id, const char* prop_name, const char* value);
dllx double steam_inventory_set_property_string_raw(void* _ptr, const char* _arg_prop_name, const char* _arg_value) {
	gml_buffer _buf(_ptr);
	SteamInventoryUpdateHandle_t _arg_handle;
	_arg_handle = _buf.read<SteamInventoryUpdateHandle_t>();
	SteamItemInstanceID_t _arg_item_id;
	_arg_item_id = _buf.read<SteamItemInstanceID_t>();
	return steam_inventory_set_property_string(_arg_handle, _arg_item_id, _arg_prop_name, _arg_value);
}

extern bool steam_inventory_remove_property(SteamInventoryUpdateHandle_t handle, SteamItemInstanceID_t item_id, const char* prop_name);
dllx double steam_inventory_remove_property_raw(void* _ptr, const char* _arg_prop_name) {
	gml_buffer _buf(_ptr);
	SteamInventoryUpdateHandle_t _arg_handle;
	_arg_handle = _buf.read<SteamInventoryUpdateHandle_t>();
	SteamItemInstanceID_t _arg_item_id;
	_arg_item_id = _buf.read<SteamItemInstanceID_t>();
	return steam_inventory_remove_property(_arg_handle, _arg_item_id, _arg_prop_name);
}

extern SteamInventoryResult_t steam_inventory_submit_update_properties(SteamInventoryUpdateHandle_t handle);
dllx double steam_inventory_submit_update_properties_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamInventoryUpdateHandle_t _arg_handle;
	_arg_handle = _buf.read<SteamInventoryUpdateHandle_t>();
	SteamInventoryResult_t _ret = steam_inventory_submit_update_properties(_arg_handle);
	_buf.rewind();
	_buf.write<SteamInventoryResult_t>(_ret);
	return 1;
}

extern bool steam_inventory_load_item_definitions();
dllx double steam_inventory_load_item_definitions_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	return steam_inventory_load_item_definitions();
}

extern optional<uint64> steam_inventory_get_item_price(SteamItemDef_t item_def);
dllx double steam_inventory_get_item_price_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamItemDef_t _arg_item_def;
	_arg_item_def = _buf.read<SteamItemDef_t>();
	optional<uint64> _ret = steam_inventory_get_item_price(_arg_item_def);
	_buf.rewind();
	_buf.write_optional<uint64>(_ret);
	return 1;
}

extern optional<vector<steam_inventory_get_item_prices_t>> steam_inventory_get_items_with_prices();
static vector<steam_inventory_get_item_prices_t> steam_inventory_get_items_with_prices_raw_vec;
dllx double steam_inventory_get_items_with_prices_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	auto _ret = steam_inventory_get_items_with_prices();
	if (!_ret.has_value()) return 0;
	steam_inventory_get_items_with_prices_raw_vec = _ret.value();
	return (double)(4 + steam_inventory_get_items_with_prices_raw_vec.size() * sizeof(steam_inventory_get_item_prices_t));
}
dllx double steam_inventory_get_items_with_prices_raw_post(void* _ptr) {
	gml_buffer _buf(_ptr);
	_buf.write_vector<steam_inventory_get_item_prices_t>(steam_inventory_get_items_with_prices_raw_vec);
	return 1;
}

extern bool steam_inventory_request_prices();
dllx double steam_inventory_request_prices_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	return steam_inventory_request_prices();
}

extern SteamInventoryResult_t steam_inventory_transfer_item_quantity(SteamItemInstanceID_t source_item_id, uint32 quantity, SteamItemInstanceID_t dest_item_id);
dllx double steam_inventory_transfer_item_quantity_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	SteamItemInstanceID_t _arg_source_item_id;
	_arg_source_item_id = _buf.read<SteamItemInstanceID_t>();
	uint32 _arg_quantity;
	_arg_quantity = _buf.read<uint32>();
	SteamItemInstanceID_t _arg_dest_item_id;
	_arg_dest_item_id = _buf.read<SteamItemInstanceID_t>();
	SteamInventoryResult_t _ret = steam_inventory_transfer_item_quantity(_arg_source_item_id, _arg_quantity, _arg_dest_item_id);
	_buf.rewind();
	_buf.write<SteamInventoryResult_t>(_ret);
	return 1;
}

extern vector<steam_get_friends_game_info_t> steam_get_friends_game_info();
static vector<steam_get_friends_game_info_t> steam_get_friends_game_info_raw_vec;
dllx double steam_get_friends_game_info_raw(void* _ptr) {
	gml_buffer _buf(_ptr);
	steam_get_friends_game_info_raw_vec = steam_get_friends_game_info();
	return (double)(4 + steam_get_friends_game_info_raw_vec.size() * sizeof(steam_get_friends_game_info_t));
}
dllx double steam_get_friends_game_info_raw_post(void* _ptr) {
	gml_buffer _buf(_ptr);
	_buf.write_vector<steam_get_friends_game_info_t>(steam_get_friends_game_info_raw_vec);
	return 1;
}

